#!/bin/bash

### BEGIN INIT INFO
# Provides:		mipi-panel-wa
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	CL-SOM-iMX8X MIPI panel initialization bug work around
### END INIT INFO

case "$1" in
start)
	echo 1 > /sys/class/graphics/fb0/blank
	echo 0 > /sys/class/graphics/fb0/blank
	;;
stop)
	bluetooth_stop
	;;
*)
cat << eom
	Usage: $0 {start|stop}
eom
	exit 1
esac

exit 0
