SRC_URI_append = " \
	file://0001-cl-som-imx8x-add-basic-support.patch \
	file://0002-sb-imx8x-add-basic-support.patch \
	file://0003-sb-imx8x-rename-node-imx8qxp-mek-to-sb-imx8x.patch \
	file://0004-sb-imx8x-rename-node-pca9555_sb.patch \
	file://0005-startek-ili9881c-Add-panel-driver.patch \
	file://0006-startek-ili9881c-cl-som-imx8x-add-panel-support.patch \
	file://0007-sb-imx8x-add-support-to-Omnivision-OV5640.patch \
	file://0008-sb-imx8x-enable-the-Goodix-touch-panel.patch \
	file://0009-sb-imx8x-enable-RS485-UART.patch \
	file://0010-sb-imx8x-add-mipi-panel-backlight.patch \
	file://defconfig \
"
