SRC_URI_append_cl-som-imx8x = " \
	file://0001-Upgrade-SCFW-API-to-v1.5-for-compatibility-with-imx-.patch	\
	file://0002-common-eeprom-eeprom_layout-and-eeprom_field-API-upd.patch	\
	file://0003-compatibility-update-common-eeprom-access-API.patch		\
	file://0004-eeprom_cmd-add-i2c_read-and-i2c_write-by-DM_I2C-prot.patch	\
	file://0005-cl-som-imx8x-Add-CL-SOM-iMX8X-board-to-U-Boot.patch		\
	file://0006-cl-som-imx8x-Add-CL-SOM-iMX8X-build-option-to-Make-t.patch	\
	file://cl-som-imx8x_defconfig 						\
"
